### ISSUE TITLE
more  designning wiki doc to let other contributors to help developing

### ISSUE THREAD

**Issue by leoxupku** [wasabia/three_dart_jsm#1]
I'm interesting in what you did in the flutter_gl three_dart and three_dart_jsm. However, three dart jsm seems a little slow behind three dart. I want the gltf/glb loader module, but I don't know how can I contribute to it. more empty interface designs will make others easily to contribute in. I'm sorry to provide suggesting by a way of creating an issue. If there is other ways to better communicate with you, hope to tell me.

**Comment by wasabia** [comment]
Hi @leoxupku 

I am very happy, if anyone contribute this project. 😄 

now gltf is supported, not full test...

i had add gltf loader example in three_dart example

but glb is not support, need draco export c api, use dart:ffi call it ???  maybe 

three_dart_jsm is just copy three.js examples/jsm, then rewrite by dart, 

about interface designs, just follow three.js as much as possible ?

if you have any idea or plan about this project. 

email: themorecolor@gmail.com
